import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import { ColorSchemeScript } from "@mantine/core";
import '@mantine/core/styles.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider withGlobalClasses withNormalizeCSS defaultColorScheme="light">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
